function success = DeployCppFilesAndBuildWorker(inDirPath)
%% Clean up the worker source subdirectory with the old translated MOD currents,
%  deploy the new autogenerated H and CPP files to the directory,
%  then build the worker.
%  inDirPath - the path to the temporary directory containing the autogenerated files.

    global remoteHPC fakeMPI

    if ispc
        if ~remoteHPC
            command = sprintf('call Core\\scripts\\win-win\\embed_mod_currents.bat "%s" %i', inDirPath, fakeMPI);
        else
            command = sprintf('call Core\\scripts\\win-lin\\embed_mod_currents.bat "%s"', inDirPath);
        end
        status = system(command);
        success = (status == 0);
    elseif isunix && ~remoteHPC
        % TODO: !!
        error('Not supported mode: isunix && ~remoteHPC');
    elseif isunix && remoteHPC
        error('Not supported mode: isunix && remoteHPC');
    else
        error('Unknown OS');
    end
    
end