function DeployCppFilesAndBuildWorker(inDirPath)
%% Clean up the worker source subdirectory with the old translated MOD currents,
%  deploy the new autogenerated H and CPP files to the directory,
%  then build the worker.
%  inDirPath - the path to the temporary directory containing the autogenerated files.

    global remoteHPC 

    if ispc
        if ~remoteHPC
            command = ['call Core\scripts\win-win\embed_mod_currents.bat ', inDirPath];
        else
            command = ['call Core\scripts\win-lin\embed_mod_currents.bat ', inDirPath];
        end
        system(command);
    elseif isunix && ~remoteHPC
        % TODO: !!
        error('Not supported mode: isunix && ~remoteHPC');
    elseif isunix && remoteHPC
        error('Not supported mode: isunix && remoteHPC');
    else
        error('Unknown OS');
    end
    
end