#!/bin/bash

# Clean up the worker source code subdirectory with the old translated MOD currents.
# Unzip the new C++ files from the archive uploaded to the cluster beforehand.
# Delete the archive.
# Build the worker.

# Run this SH-script with one argument specifying the archive name

# Clean up the worker source code subdirectory containing the old autogenerated C++ code for MOD corrents
cd ../ModCurrents/Autogenerated
rm * -f

# Unzip the new files from the archive, then delete the archive
cd ..
echo "Unzipping C++ files ..."
unzip $1.zip -d Autogenerated > /dev/null
rm $1.zip -f

# Build the worker
cd ../build
echo "Building HPC kernel in Release configuration ..."
sh lin_release.sh
