@echo off

rem Compare the old hash code for the MOD currents with the new one.
rem If they are equal, then exit (we don't need to rebuild the worker).
rem Otherwise, clean up the worker source subdirectory with the old translated MOD currents.
rem Then deploy the new autogenerated H and CPP files to the directory
rem and build the worker in Debug configuration.

rem Run this BAT-script with three arguments specifying:
rem 1) the name of the local directory with the autogenerated C++ files,
rem 2) the new hash code file name,
rem 3) the flag (1/0) indicating whether to build the code in "FakeMPI" configuration.

rem Initialize variables
call Core\scripts\win-win\params.bat

set AUTOGENFILESDIR=%MATLABHOSTDIR%\%1

rem Go to the translated MOD currents source code directory
cd %WORKERDIR%\ModCurrents\Autogenerated

rem Check the hash code file name
where /Q %2

if %ERRORLEVEL% == 0 (
    echo Don't need to rebuild the worker.
) else (
    rem Delete all the old files
    del * /Q
    
    rem Create an empty file with the new hash code in name
    copy NUL %2
    
    rem Copy the new autogenerated source code files
    xcopy %AUTOGENFILESDIR%\* %WORKERDIR%\ModCurrents\Autogenerated /Y /Q > NUL
    
    rem Go to the build scripts directory
    cd %WORKERDIR%\build
    
    rem Build the worker
    if %3 == 0 (
        echo Building HPC kernel in Debug configuration ...
        call win_debug.bat 1
    ) else (
        echo Building HPC kernel in FakeMPIDebug configuration ...
        call win_fakeMPI_debug.bat 1
    )
)
