@echo on

rem Clean up the worker source subdirectory with the old translated MOD currents.
rem Then deploy the new autogenerated H and CPP files to the directory.
rem Then build the worker in Release configuration.

rem Run this BAT-script with one argument specifying the path to the directory with the autogenerated C++ files.

rem Initialize variables
call Core\scripts\win-win\params.bat

rem Go to the translated MOD currents source code directory
cd %WORKERDIR%\ModCurrents\Autogenerated

rem Delete all the old files
del * /Q

rem Copy the new autogenerated source code files
xcopy %1\* %WORKERDIR%\ModCurrents\Autogenerated /Y /Q

rem Build the worker
cd %WORKERDIR%\build
call win_release.bat