@echo off

rem Clean up the worker source subdirectory with the old translated MOD currents.
rem Then deploy the new autogenerated H and CPP files to the directory.
rem Then build the worker in Debug configuration.

rem Run this BAT-script with two arguments specifying:
rem 1) the path to the directory with the autogenerated C++ files,
rem 2) the flag (1/0) indicating whether to build the code in "FakeMPI" configuration.

rem Initialize variables
call Core\scripts\win-win\params.bat

rem Go to the translated MOD currents source code directory
cd %WORKERDIR%\ModCurrents\Autogenerated

rem Delete all the old files
del * /Q

rem Copy the new autogenerated source code files
xcopy %1\* %WORKERDIR%\ModCurrents\Autogenerated /Y /Q > NUL

rem Build the worker
cd %WORKERDIR%\build
if %2 == 0 (
    echo Building HPC kernel in Debug configuration ...
    call win_debug.bat 1
) else (
    echo Building HPC kernel in FakeMPIDebug configuration ...
    call win_fakeMPI_debug.bat 1
)