@echo off

rem Zip the autogenerated files with C++ code for MOD curents.
rem Upload the archive to the cluster, then delete its local copy.
rem Then call the helper remote script that will do the following:
rem 1) clean up the worker source code subdirectory with the old translated MOD currents,
rem 2) unzip the new files from the archive and delete the archive,
rem 3) build the worker.

rem Run this BAT-script with one argument specifying the path to the local directory with the autogenerated C++ files.

rem Initialize variables
call Core\scripts\win-lin\params.bat

rem Set archive name
set ARCHIVENAME=AutogenCppCode

rem Check if an old archive exists, if so -- delete
if exist "%1\%ARCHIVENAME%.zip" del "%1\%ARCHIVENAME%.zip"

rem Create ZIP archive
echo Zipping C++ files ...
"%THIRDPARTYDIR%\7za.exe" a "%1\%ARCHIVENAME%.zip" -r "%1\*" > NUL

rem Go to 3rd party software directory containing pscp.exe and plink.exe
cd %THIRDPARTYDIR%

rem Upload ZIP-file to the head node of HPC cluster
echo Uploading ZIP archive ...
pscp -pw %PASSWORD% "%1\%ARCHIVENAME%.zip" %LOGIN%@%HEADNODEIP%:"%HEADNODEWORKERDIR%/ModCurrents" > NUL

rem Delete the local archive
del "%1\%ARCHIVENAME%.zip"

rem Call the helper remote script
plink -pw %PASSWORD% %LOGIN%@%HEADNODEIP% cd \"%HEADNODEWORKERDIR%/scripts\"; sh embed_mod_currents.sh %ARCHIVENAME%
