@echo off

set HEADNODEIP=144.82.46.83
set LOGIN=reviewer
set PASSWORD=reviewer1
set "HEADNODEWORKERDIR=/home/reviewer/worker"

set MATLABHOSTDIR=%cd%
set THIRDPARTYDIR=%MATLABHOSTDIR%\Core\3rdparty

set "REMOTESCRIPTSDIR=%HEADNODEWORKERDIR%/scripts"

set "REMOTESCRIPTSBUILD=%HEADNODEWORKERDIR%/build"