function success = DeployCppFilesAndBuildWorker(tempDirName)
%% Check whether the old autogenerated code for MOD files became obsolet.
%  If so, clean up the worker source subdirectory with the old translated MOD currents,
%  deploy the new autogenerated H and CPP files to the directory,
%  then build the worker.
%  tempDirName - name of the temporary directory containing the autogenerated files.

    global remoteHPC fakeMPI
    
    % Compute MD5-code based on content of the selected MOD-files and values of the assigned parameters
    hashStr = GetMD5ForModData();
    md5FileName = [hashStr, '.md5'];
    
    if ispc
        if ~remoteHPC
            command = sprintf('call Core\\scripts\\win-win\\embed_mod_currents.bat %s %s %i', tempDirName, md5FileName, fakeMPI);
        else      
            command = sprintf('call Core\\scripts\\win-lin\\embed_mod_currents.bat %s %s', tempDirName, md5FileName);
        end       
        status = system(command);
        success = (status == 0);
    elseif isunix && ~remoteHPC
        % TODO: !!
        error('Not supported mode: isunix && ~remoteHPC');
    elseif isunix && remoteHPC
        error('Not supported mode: isunix && remoteHPC');
    else
        error('Unknown OS');
    end
    
end