function BasicParams()

    global remoteHPC availableNodes useGUI
    global debugMode
    
    % Structs
    global GuiTypes ScmTypes SclModels
    
    % Whether to conduct simulation on remote HPC cluster
    remoteHPC = true;
    
    % Names of all cluster nodes you may want to use in simulation
    availableNodes = {'tuxm1', ...
                      'tuxm2', ...
                      'tuxm3', ...
                      'tuxm4', ...
                      'tuxm5', ...
                      'tuxm6', ...
                      'tuxm7', ...
                      'tuxm8', ...
                      'tuxm9', ...
                      'tuxm10', ...
                      'tuxm11', ...
                      'tuxm12'};
    
    % Whether to use Graphic User Interface to prepare input parameters
    useGUI = true;
    
    debugMode = false;
    
    %% Structs
    
    GuiTypes = struct('StartFromScratch', 1, ...
                      'ContinueOldSession', 2, ...
                      'MonitorBackgroundProcess', 3, ...
                      'TakeOutputData', 4, ...
                      'ScriptTakeSnapshot', 5, ...
                      'UtilityPlotStdpModels', 6, ...
                      'UtilityComputeMaxModelSize', 7);
    
    ScmTypes = struct('AllZeros', 1, 'AllEqual', 2, 'HstDense', 3, 'HstSparse', 4, 'KrnDense', 5, 'KrnSparse', 6, 'KrnOneBit', 7, 'KrnInPlace', 8);
    
    SclModels = struct('BSS', 1, 'BSD', 2);
    
end