@echo off

rem Get the old hash code file located on the cluster.
rem Compare its name with the new hash code.
rem If they are equal, then exit (we don't need to rebuild the worker).
rem Otherwise, zip the autogenerated files with C++ code for MOD curents.
rem Upload the archive to the cluster, then delete its local copy.
rem Call the helper remote script that will do the following:
rem 1) clean up the worker source code subdirectory with the old translated MOD currents,
rem 2) unzip the new files from the archive and delete the archive,
rem 3) build the worker.

rem Run this BAT-script with two arguments specifying:
rem 1) the name of the local directory with the autogenerated C++ files,
rem 2) the new hash code file name.

rem Initialize variables
call Core\scripts\win-lin\params.bat

rem Set the archive name and the temporary directory path
set ARCHIVENAME=AutogenCppCode
set AUTOGENFILESDIR=%MATLABHOSTDIR%\%1

rem Check if an old archive exists, if so -- delete
cd %AUTOGENFILESDIR%
if exist %ARCHIVENAME%.zip del %ARCHIVENAME%.zip

rem Go to 3rd party software directory containing pscp.exe and plink.exe
cd %THIRDPARTYDIR%

rem Download MD5-file from HPC cluster to the host machine
pscp -pw %PASSWORD% %LOGIN%@%HEADNODEIP%:"%HEADNODEWORKERDIR%/ModCurrents/Autogenerated/%2" "%AUTOGENFILESDIR%" > NUL

rem Check the hash code file name
cd %AUTOGENFILESDIR%
where /Q %2

if %ERRORLEVEL% == 0 (
    echo Don't need to rebuild the worker.
) else (
    rem Create an empty file with the hash code in name
    copy NUL %2

    rem Go to 3rd party software directory containing pscp.exe and plink.exe
    cd %THIRDPARTYDIR%

    rem Create ZIP archive
    echo Zipping C++ files ...
    7za a "..\..\%1\%ARCHIVENAME%.zip" -r "..\..\%1\*" > NUL

    rem Upload ZIP-file to the head node of HPC cluster
    echo Uploading ZIP archive ...
    pscp -pw %PASSWORD% "..\..\%1\%ARCHIVENAME%.zip" %LOGIN%@%HEADNODEIP%:"%HEADNODEWORKERDIR%/ModCurrents" > NUL

    rem Delete the local archive
    del "%AUTOGENFILESDIR%\%ARCHIVENAME%.zip"

    rem Call the helper remote script
    plink -pw %PASSWORD% %LOGIN%@%HEADNODEIP% cd \"%HEADNODEWORKERDIR%/scripts\"; sh embed_mod_currents.sh %ARCHIVENAME%
)
